'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import AboutSection from '@/components/AboutSection';
import PracticeAreasSection from '@/components/PracticeAreasSection';
import PortfolioSection from '@/components/PortfolioSection';
import ProcessSection from '@/components/ProcessSection';
import WhyChooseUsSection from '@/components/WhyChooseUsSection';
import BookingSection from '@/components/BookingSection';
import CTASection from '@/components/CTASection';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <AboutSection />
        <PracticeAreasSection />
        <PortfolioSection />
        <ProcessSection />
        <WhyChooseUsSection />
        <BookingSection />
        <CTASection />
        <Footer />
      </main>
    </>
  );
}