'use client';

import React from 'react';
import Hero from '@/components/Hero';
import About from '@/components/About';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 w-full min-h-screen">
        {/* Components generated by the builder will be added here */}
      
        <Hero />
        <About />
      </main>
    </>
  );
}
